version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:12

  nginx:
    image: nginx:latest
    ports: "9999:9999"
