version: '3.1'

services:
  api01:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  db:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: rinha
      MONGO_INITDB_ROOT_PASSWORD: senhasecreta
    ports: 
      - 27017:27017

  nginx:
    image: nginx:latest
    ports: 
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"